[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "videollama2"
version = "1.0"
description = "Release of VideoLLaMA2"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
]

[project.optional-dependencies]
train = ["ninja"]

[project.urls]
"Homepage" = "https://github.com/DAMO-NLP-SG/VideoLLaMA2"
"Bug Tracker" = "https://github.com/DAMO-NLP-SG/VideoLLaMA2/issues"

[tool.setuptools.packages.find]
exclude = ["assets*", "benchmark*", "docs", "dist*", "playground*", "scripts*", "tests*"]

[tool.wheel]
exclude = ["assets*", "benchmark*", "docs", "dist*", "playground*", "scripts*", "tests*"]
